services:
  backend:
    build:
      context: ./Server
    env_file:
      - ./Server/.env
    ports:
      - "4000:4000"
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/mission4
    ports:
      - "5173:80"
    restart: unless-stopped
